<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MoviesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $movies = [
            ['name' => 'The Shawshank Redemption'],
            ['name' => 'The Godfather'],
            ['name' => 'The Dark Knight'],
            ['name' => 'Pulp Fiction'],
            ['name' => 'Forrest Gump'],
            ['name' => 'Inception'],
            ['name' => 'Fight Club'],
            ['name' => 'The Matrix'],
            ['name' => 'Goodfellas'],
            ['name' => 'The Lord of the Rings: The Return of the King'],
            ['name' => 'Star Wars: Episode IV - A New Hope'],
            ['name' => 'One Flew Over the Cuckoo\'s Nest'],
            ['name' => 'Seven Samurai'],
            ['name' => 'The Silence of the Lambs'],
            ['name' => 'City of God'],
            ['name' => 'The Usual Suspects'],
            ['name' => 'Se7en'],
            ['name' => 'The Lion King'],
            ['name' => 'The Dark Knight Rises'],
            ['name' => 'Casablanca'],
            ['name' => 'Schindler\'s List'],
            ['name' => 'The Departed'],
            ['name' => 'Whiplash'],
            ['name' => 'The Prestige'],
            ['name' => 'The Good, the Bad and the Ugly'],
            ['name' => 'The Intouchables'],
            ['name' => 'Spirited Away'],
            ['name' => 'The Pianist'],
            ['name' => 'The Green Mile'],
            ['name' => 'Interstellar'],
            ['name' => 'Gladiator'],
            ['name' => 'Django Unchained'],
            ['name' => 'WALL-E'],
            ['name' => 'The Great Dictator'],
            ['name' => 'Psycho'],
            ['name' => 'The Shining'],
            ['name' => 'The Social Network'],
            ['name' => 'A Clockwork Orange'],
            ['name' => 'The Breakfast Club'],
            ['name' => 'The Avengers'],
            ['name' => 'The Incredibles'],
            ['name' => 'Reservoir Dogs'],
            ['name' => 'The Wolf of Wall Street'],
            ['name' => 'Mad Max: Fury Road'],
            ['name' => 'The Grand Budapest Hotel'],
            ['name' => 'The Shape of Water'],
            ['name' => 'Moonlight'],
            ['name' => 'The Sixth Sense'],
            ['name' => 'Inside Out'],
            ['name' => 'Braveheart'],
            ['name' => 'Joker'],
            ['name' => 'No Country for Old Men'],
            ['name' => 'Titanic'],
            ['name' => 'Jurassic Park'],
            ['name' => 'The Exorcist'],
            ['name' => 'The Truman Show'],
            ['name' => 'Back to the Future'],
            ['name' => 'Eternal Sunshine of the Spotless Mind'],
            ['name' => 'The Big Lebowski'],
            ['name' => 'The Wizard of Oz'],
            ['name' => 'The Help'],
            ['name' => 'The Secret in Their Eyes'],
            ['name' => 'The Curious Case of Benjamin Button'],
            ['name' => 'Black Swan'],
            ['name' => 'Gone Girl'],
            ['name' => 'Her'],
            ['name' => 'The Florida Project'],
            ['name' => 'Your Name'],
            ['name' => 'Coco'],
            ['name' => 'Lady Bird'],
            ['name' => 'Parasite'],
            ['name' => 'Soul'],
            ['name' => 'The Farewell'],
            ['name' => 'Portrait of a Lady on Fire'],
            ['name' => 'Nomadland'],
            ['name' => 'Fargo'],
            ['name' => 'Birdman'],
            ['name' => 'The Artist'],
            ['name' => 'The King\'s Speech'],
            ['name' => 'There Will Be Blood'],
            ['name' => 'The Shape of Water'],
            ['name' => 'The Lives of Others'],
            ['name' => 'The Deer Hunter'],
            ['name' => 'The Great Escape'],
            ['name' => 'Reservoir Dogs'],
            ['name' => 'The Hunt'],
            ['name' => 'Trainspotting'],
            ['name' => 'The Lobster'],
            ['name' => 'A Beautiful Mind'],
            ['name' => 'The Thing'],
            ['name' => 'The Secret Life of Pets'],
            ['name' => 'Arrival'],
            ['name' => 'A Star Is Born'],
            ['name' => 'The Nightingale'],
            ['name' => 'Wild Strawberries'],
            ['name' => 'The Bridge on the River Kwai'],
            ['name' => 'Ladri di biciclette'],
            ['name' => 'The Pianist'],
            ['name' => 'The Hunt for Red October'],
            ['name' => 'Amour'],
            ['name' => 'The Others'],
            ['name' => 'The Butterfly Effect'],
            ['name' => 'Memento'],
            ['name' => 'Lost in Translation'],
            ['name' => 'The Invisible Man'],
            ['name' => 'Twelve Angry Men'],
            ['name' => 'The Social Network'],
            ['name' => 'The Girl with the Dragon Tattoo'],
            ['name' => 'The Thing'],
            ['name' => 'The Graduate'],
            ['name' => 'Trainspotting'],
            ['name' => 'The Last Samurai'],
            ['name' => 'Snowpiercer'],
            ['name' => 'Gangs of New York'],
            ['name' => 'Dune'],
            ['name' => 'Howl\'s Moving Castle'],
            ['name' => 'A Ghost Story'],
            ['name' => 'The Lobster'],
            ['name' => 'Prisoners'],
            ['name' => 'Shutter Island'],
            ['name' => 'The Illusionist'],
            ['name' => '12 Years a Slave'],
            ['name' => 'Tangled'],
            ['name' => 'The Hangover'],
            ['name' => 'Crazy Rich Asians'],
            ['name' => 'Zodiac'],
            ['name' => 'Blue is the Warmest Color'],
            ['name' => 'Searching'],
            ['name' => 'Spotlight'],
            ['name' => 'Lady Bird'],
            ['name' => 'The Favourite'],
            ['name' => 'Get Out'],
            ['name' => 'La La Land'],
            ['name' => 'The Edge of Seventeen'],
            ['name' => 'Midsommar'],
            ['name' => 'A Ghost Story'],
            ['name' => 'The Farewell'],
            ['name' => 'Knives Out'],
            ['name' => 'Black Panther'],
            ['name' => 'Spider-Man: Into the Spider-Verse'],
            ['name' => 'Avengers: Endgame'],
            ['name' => '1917'],
            ['name' => 'The Trial of the Chicago 7'],
            ['name' => 'Palm Springs'],
            ['name' => 'Sound of Metal'],
            ['name' => 'Nomadland'],
            ['name' => 'Dune'],
            ['name' => 'The Power of the Dog'],
            ['name' => 'West Side Story'],
            ['name' => 'Licorice Pizza'],
            ['name' => 'Everything Everywhere All at Once'],
            ['name' => 'Top Gun: Maverick'],
            ['name' => 'Avatar: The Way of Water'],
        ];
        DB::table('movies')->insert($movies);
    }
}
